package com.example.ytdlpdownloader.app

// BuildConfig is auto-generated by the build system.
// This file just documents available fields for reference:
// BuildConfig.DEBUG  - true in debug builds
// BuildConfig.VERSION_NAME - e.g. "1.0.0"
// BuildConfig.APPLICATION_ID - "com.example.ytdlpdownloader"
